version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres-contacts
    ports:
      - '5566:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'contacts_prod'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  contacts:
    image: contacts-demo
    container_name: contacts-demo
    build: .
    ports:
      - 4000:4000
    network_mode: "host"
    depends_on:
      - "postgres"
